### ISSUE TITLE
Feat: Footer 

### ISSUE THREAD

**Issue by hookor** [7-7-2/DDOCKER#10]
## ☕ 기능

![image](https://github.com/7-7-2/DDOCKER/assets/115582699/c7a38ab8-34bc-40ad-adf5-aaf831e5feee)

## 🪴 TODO

- [x] Fix: Footer 구조에 일치시킨 header구조로 수정 및 Footer 기본 페이지별 헤더 생성
- [x] Feat: Footer navigation
- [x] Feat: 헤더 및 푸터 조건부 렌더링 atoms 추가 및 hooks생성
- [x] Feat: 24-size icon 유틸함수 분리
- [x] Remove: 디자인 변경으로 인한 컴포넌트 제거
- [x] Feat: : 모바일웹 스케일 조정 및 터치 환경 css 추가
