### ISSUE TITLE
 Feat: Initial Form

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker#23]
## ☕ 기능
<img width="232" alt="image" src="https://github.com/7-7-2/DDOCKER/assets/125563995/38b19f0f-b313-45c0-b2e0-330e547532c5">
<img width="219" alt="image" src="https://github.com/7-7-2/DDOCKER/assets/125563995/10c9d727-1191-4866-83ea-4666d2dc78c7">

- initial form component

## 🪴 TODO

- [x] Feat: SelectFavBrand  component
- [x] Desgin: initial Form
- [x] Design: SelectFavBrand
- [x] Design: Button style 추가
- [x] Feat: initialInfo 
- [x] Feat: SelectGender component
- [x] Fix: signin page 수정
