### ISSUE TITLE
 Refactor: Profile Page

### ISSUE THREAD

**Issue by swon95** [7-7-2/DDocker#25]
## ☕ 기능

- 프로필 페이지 내 기능 수정
  - Grid 요소 및 `width` 값 재설정
<img width="300" alt="image" src="https://github.com/7-7-2/DDocker/assets/96659041/533c4d8e-0a4d-4349-a847-5f786e4e3506">
<img width="300" alt="image" src="https://github.com/7-7-2/DDocker/assets/96659041/4bf70314-e6a4-415c-a96f-7ca4c0cd4be3">

</br>

  - MyPage `input`, `Header` 요소 삽입
    - FileRoader 👉 프로필 이미지 등록
<img width="300" alt="image" src="https://github.com/7-7-2/DDocker/assets/96659041/04816d6a-6431-48f0-883b-630cd712d0ba">

<img width="200" alt="image" src="https://github.com/7-7-2/DDocker/assets/96659041/5d433ab1-db0d-49b3-a523-0c52087093f9">

<img width="250" alt="image" src="https://github.com/7-7-2/DDocker/assets/96659041/8d17ce15-170e-4aec-a543-57ff3aa55232">

## 🪴 TODO

- [x] Design: CSS Modify
- [x] Refactor: Header area Apply
- [ ] Feat: Users Profile
- [ ] Feat: ImgProfile
