### ISSUE TITLE
 Feat: Search Page

### ISSUE THREAD

**Issue by swon95** [7-7-2/DDocker#30]
## ☕ 기능

- 검색 페이지 내 기능 구현

<img width="300" alt="image" src="https://github.com/7-7-2/DDocker/assets/96659041/5035534a-4691-4645-a63b-8367bff6437c">
<img width="300" alt="image" src="https://github.com/7-7-2/DDocker/assets/96659041/ff94826e-1d79-4420-9338-754bad472c17">

## 🪴 TODO

- [x] Feat: Search Bar Component
- [x] Feat: Search Bar Conditional Rendering
- [x] Feat: Search ListItem Component
- [x] Feat: Recent Search History & Delete
- [x] Feat: Other User Management (useParams)
