### ISSUE TITLE
 Feat: WaterPerCoffee

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker#32]
## ☕ 기능
<img width="611" alt="image" src="https://github.com/7-7-2/DDocker/assets/125563995/195ece40-b3d0-4f6e-af3f-ed513f879045">

- WaterPerCoffee 및 Home page layout

## 🪴 TODO

- [x] Design:TodayCaffeineInfo component
- [x] Design: WaterPerCoffee component
- [x] Design: Home page svg,png 추가
- [x] Feat: TodayCaffeineInfo component
- [x] Feat: WaterPerCoffee component
- [x] Feat: CoffeeIntake component
