### ISSUE TITLE
 Feat: Profile Component

### ISSUE THREAD

**Issue by swon95** [7-7-2/DDOCKER#4]
## ☕ 기능

- Profile Component 기능 구현 및 스타일링 작업 진행

<img width="300" alt="image" src="https://github.com/7-7-2/772temp/assets/96659041/682f2f0e-f32e-4f22-8266-41933add54fb">
<img width="300" alt="image" src="https://github.com/7-7-2/772temp/assets/96659041/ee6c3180-4e9a-42eb-a19f-05d146b45f21">

## 🪴 TODO

- [x] Feat: Profile Component 생성
- [x] Design: Profile Component Style 작업
- [x] Feat: Profile 컴포넌트 기능 구현
- [x] Feat: ProfileImg 컴포넌트 기능 구현
- [x] Feat: FollowCount 컴포넌트 기능 구현
- [x] Feat: ProfileDetail 컴포넌트 기능 구현
- [x] Feat: Profile Grid 기능 구현
