### ISSUE TITLE
 Feat: PWA cache storage, caffeine Filter 기능

### ISSUE THREAD

**Issue by cuconveniencestore** [7-7-2/DDocker#59]
## ☕ 기능

- PWA 적용을 위한 cache storage 저장 로직 추가
- caffeine Filter 기능 구현

## 🪴 TODO

- [x] Feat: useSetCacheData
- [x] Feat: useGetCacheData
- [x] Feat: firebase 로직에 cacheData 저장 로직 추가
- [x] Feat: coffeeMenuSelection 로직
- [x] Docs: coffeeData update
- [x] Feat: postRegistData atom, Postregister.tsx에 추가
- [x] Feat: usl 추가 state 수정
- [x] Feat: caffeine Filter data post register page 연결
- [x] Feat: caffeine Filter 기능
- [x] Feat: coffeeMenuSelection 기눙
- [x] Feat: caffeine option selection 기능
- [x] Fix: cacheData 관련 수정 및 startPage Layout 수정
