### ISSUE TITLE
Fix: layout 

### ISSUE THREAD

**Issue by hookor** [7-7-2/DDocker#62]
## ☕ 기능

- useShowfooter Hook 호출시 useLayoutEffect 내부 clean-up function 미작성으로 인해 페이지 이동시 푸터 사라짐 수정
- iOS vh미동작 및 safe-area로 인한 레이아웃 계산 수정
- Header 및 Footer내 lazy loading시 Suspense 미작성으로 인한 에러 수정

## 🪴 TODO

- [ ] Feat: useShowfooter clean-up
- [ ] Feat: iOS dvh && safe-area inset padding
- [ ] Feat: Layout Suspense
