### ISSUE TITLE
Fix: build

### ISSUE THREAD

**Issue by hookor** [7-7-2/DDocker#65]
## ☕ 기능

[Screen recording 2023-12-22 6.11.21 AM.webm](https://github.com/7-7-2/DDocker/assets/115582699/5c09e764-be17-419a-bd89-6a941dc67c3a)

- remove unused imports 
- 뒤로 가기 수정
- NoticeItem 토글 수정
- Header style
- 미사용 hooks 제거

## 🪴 TODO

- [ ] Fix: remove unused imports 
- [ ] Fix: remove unused hooks
- [ ] Fix: useNavigateTo back
- [ ] Fix: Header style
- [ ] Fix: NoticeItem toggle
