### ISSUE TITLE
Feat: Header 

### ISSUE THREAD

**Issue by hookor** [7-7-2/DDOCKER#9]
## ☕ 기능

![image](https://github.com/7-7-2/DDOCKER/assets/115582699/60acace4-a4fa-434e-8993-221c8904914b)
 
![image](https://github.com/7-7-2/DDOCKER/assets/115582699/948d974a-2a1d-4d17-b1e4-96b2d24aedfa)

## 🪴 TODO

- [x] 헤더 사용 페이지별 필요기능 고려 설계(left, center, right)
- [x] Feat: Header svg Icons 
- [x] Feat: Header navigation hooks
- [x] Feat: props and types
- [x] Feat: Header && Header Icon components
- [x] Feat: Router dynamic segments
